### ISSUE TITLE
No issues just wanted to contact you


### ISSUE THREAD

**Issue by 1972CL** [BanDroid/Simple-Fighting-Games-w-Python#1]
Hey there how are you doing? I saw you on GitHub on deadly jack Acode development page. I've been trying to use that app with little success. I'm pretty much totally illiterate with computers and understanding code and the like. Hey I was wondering if you would be interested in helping me make a save game editor for a game I play. I'd certainly be interested in doing that and I would pay you for it as well. Would you be interested in that? Hope to hear back from you. Have a good day

**Comment by BanDroid** [comment]
@1972CL could you explain more? And do you have telegram? If yes, then you could message me directly in telegram so it is much easier
https://t.me/BanDroid_official
